# Generated by Django 4.2.3 on 2023-07-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_news_news_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_date',
        ),
    ]
