# Generated by Django 4.2.3 on 2023-07-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-news_date']},
        ),
    ]
